apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crcbundles.crc.developer.openshift.io
spec:
  group: crc.developer.openshift.io
  names:
    kind: CrcBundle
    listKind: CrcBundleList
    plural: crcbundles
    singular: crcbundle
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CrcBundle is the Schema for the crcbundles API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CrcBundleSpec defines the desired state of CrcBundle
            properties:
              diskSize:
                description: DiskSize is the size of the disk in this bundle
                type: string
              image:
                description: Image is the container image containing the VM image
                  for this bundle
                type: string
              kubeconfig:
                description: Kubeconfig is the base64 encoded initial kubeconfig to
                  connect to this bundle
                type: string
              sshKey:
                description: SSHKey is the base64 encoded SSH key used to connect
                  to the Node in this bundle
                type: string
            required:
            - diskSize
            - image
            - kubeconfig
            - sshKey
            type: object
          status:
            description: CrcBundleStatus defines the observed state of CrcBundle
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
